### ISSUE TITLE
Specify number of parallel calculations to be submitted

### ISSUE THREAD

**Issue by jeveki** [reproducible-reporting/parman#25]
Is there a way to specify the max number of calculations that can be submitted at once to the (Concurrent)Runner? For example to enable rapid prototyping on a debugging cluster (Donphan) that has heavy restrictions on the number of parallel jobs.

**Comment by tovrstra** [comment]
Yes, this can be done by specifying the nummer of tasks in the executor. Each task will only submit one job and wait for it to complete.

For example, the following will never submit more than 8 jobs:

```python
ConcurrentRunner(schedule=schedule, executor=ThreadPoolExecutor(max_workers=8))
```

I believe it is safer to use the `ThreadPoolExecutor` than the `ProcessPoolExecutor`. (You should get a warning as of Python 3.12 for using the wrong one.)
