### ISSUE TITLE
jobinfo.py typechecking of object with changing length

### ISSUE THREAD

**Issue by lcdumort** [reproducible-reporting/parman#6]
I'm currently stuck a bit on the `jobinfo.py`

To give a bit of context:
for the active learning loop, I have a list of `Path` 's that point to reference calculations.
The idea is then that these are included in a AMS `DataSet`.
I would therefore expect the `jobinfo.py` file to be something like this:
```python
from pathlib import Path, PosixPath

def get_result_mock(structures: [Path]):
    return [Path("__dataset__"), Path("__jobcollection__")]
````

However, since the length of the structure part is fluctuating (i.e. at boot it contains quite 10+ paths, while in the active learning step this is 1-3 per step) it fails at the typechecking:
```
TypeError: parameters at ('kwargs', 'structures'): cannot type-check [PosixPath('g00/compute/0000/calculations.json'), PosixPath('g00/compute/0001/calculations.json'), PosixPath('g00/compute/0002/calculations.json')] with [<class 'pathlib.Path'>]
```

I've seen that in the example this is cleverly used by looping in the main function whenever an object has changing lengths. In this case, however, this would mean a huge overhead since importing stuff from scm.plams and scm.params in general takes quite some time while the actual operation (i.e. adding an entry) is very short.

**Comment by lcdumort** [comment]
Note: I'm not on the latest version (still on sweetfuture, not parman at the moment)

**Comment by tovrstra** [comment]
The following subtle change, `list[Path]`, fixes it:

```python
from pathlib import Path, PosixPath

def get_result_mock(structures: list[Path]):
    return [Path("__dataset__"), Path("__jobcollection__")]
```
